### ISSUE TITLE
OOM on 5090 Precompression Error

### ISSUE THREAD

**Issue by CKay010** [ace-step/ACE-Step-1.5#154]
I'm getting an OOM error when trying to create the precompression.
i'm using latest portable ace-step.

specs
5090
64sys memory

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.66 GiB. GPU 0 has a total capacity of 31.84 GiB of which 0 bytes is free. Of the allocated memory 26.86 GiB is allocated by PyTorch, with 59.00 MiB allocated in private pools (e.g., CUDA Graphs), and 3.60 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by cool9-MK** [comment]
I have the same problem on a 5070ti 16GB when generating with the 4B model. It's as if CPU offloading isn't working properly.
I solved the problem by switching the LLM backend from vllm to pt. But I don't know how much this affects the generation quality.

**Comment by DumoeDss** [comment]
What models are used, and what tasks are handled? The 4B lm typically requires 32G memory to handle text2music tasks, while cover tasks will require more.

**Comment by CHKE9** [comment]
**Found the solution**: this GUI is designed for **three steps** first, generating music; second, creating the LoRA dataset; and third, training the LoRA. You should only do one task at a time. Trying to generate music and then immediately make a dataset or train a LoRA will cause an OOM error because your VRAM and RAM are already in use, preventing further generations. So, if you’re generating music, just stick to that. If you’re making a dataset, only do that. The same goes for LoRA training completely close the app (terminal) and restart it for each step; otherwise, you’ll hit OOM errors. 

For training LoRAs, initialize without checking any options just select the models and don’t enable “Initialize 5Hz LM,” “Flash,” “Offload,” etc. For dataset creation, enable “Initialize 5Hz LM” and use flash attention.
