### ISSUE TITLE
OOM with API server at model init

### ISSUE THREAD

**Issue by hum-ma** [ace-step/ACE-Step-1.5#166]
Trying to run the API server results in torch.OutOfMemoryError

Should be possible to run on GPU with 4GB VRAM (and in ComfyUI it works though the 1.7b LM is very slow with offloading).

 - Linux
 - PyTorch 2.9.1
 - CUDA 12.4
 - Nvidia GTX 970

Run in a venv with `python -m acestep.api_server`

<details>

<summary>Log and stack trace</summary>

```
2026-02-05 17:09:38.465 | WARNING  | acestep.training.lora_utils:<module>:26 - PEFT library not installed. LoRA training will not be available.
2026-02-05 17:09:38.467 | WARNING  | acestep.training.data_module:<module>:23 - Lightning not installed. Training module will not be available.
2026-02-05 17:09:38.469 | WARNING  | acestep.training.trainer:<module>:25 - Lightning Fabric not installed. Training will use basic training loop.
INFO:     Started server process [26488]
INFO:     Waiting for application startup.
2026-02-05 17:09:38.787 | INFO     | acestep.handler:initialize_service:399 - [initialize_service] Attempting to load model with attention implementation: sdpa
2026-02-05 17:09:40.560 | INFO     | acestep.handler:initialize_service:427 - [initialize_service] Keeping main model on cuda (persistent)
2026-02-05 17:09:44.894 | ERROR    | acestep.handler:initialize_service:529 - [initialize_service] Error initializing model
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code

  File "/home/hum/gradioenv/ACE-Step-1.5/acestep/api_server.py", line 2430, in <module>
    main()
    └ <function main at 0x7fa5a554d8a0>

  File "/home/hum/gradioenv/ACE-Step-1.5/acestep/api_server.py", line 2421, in main
    uvicorn.run(
    │       └ <function run at 0x7fa5a54dc860>
    └ <module 'uvicorn' from '/home/hum/gradioenv/lib/python3.13/site-packages/uvicorn/__init__.py'>

  File "/home/hum/gradioenv/lib/python3.13/site-packages/uvicorn/main.py", line 594, in run
    server.run()
    │      └ <function Server.run at 0x7fa5a54dc0e0>
    └ <uvicorn.server.Server object at 0x7fa5a53006e0>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio_run(self.serve(sockets=sockets), loop_factory=self.config.get_loop_factory())
           │           │    │             │                      │    │      └ <function Config.get_loop_factory at 0x7fa5a54aba60>
           │           │    │             │                      │    └ <uvicorn.config.Config object at 0x7fa5a53001a0>
           │           │    │             │                      └ <uvicorn.server.Server object at 0x7fa5a53006e0>
           │           │    │             └ None
           │           │    └ <function Server.serve at 0x7fa5a54dc180>
           │           └ <uvicorn.server.Server object at 0x7fa5a53006e0>
           └ <function run at 0x7fa65c0962a0>
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           │      │   └ <coroutine object Server.serve at 0x7fa5a54e8040>
           │      └ <function Runner.run at 0x7fa65bf70720>
           └ <asyncio.runners.Runner object at 0x7fa5a5300980>
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /home/hum/gradioenv/lib/python3.13/site-packages/uvicorn/server.p...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x7fa65bf6e2a0>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7fa5a5300980>
  File "/usr/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fa65bf6e200>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fa65bf70040>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.13/asyncio/base_events.py", line 2042, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fa65c097100>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7fa5a56cf3a0>()>
  File "/usr/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7fa5a56cf3a0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7fa5a56cf3a0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7fa5a56cf3a0>()>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/uvicorn/lifespan/on.py", line 86, in main
    await app(scope, self.receive, self.send)
          │   │      │    │        │    └ <function LifespanOn.send at 0x7fa5a54f5b20>
          │   │      │    │        └ <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>
          │   │      │    └ <function LifespanOn.receive at 0x7fa5a54f5bc0>
          │   │      └ <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>
          │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fa5a55efb60>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/uvicorn/middleware/proxy_headers.py", line 29, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
                 │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
                 │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
                 │    └ <fastapi.applications.FastAPI object at 0x7fa5a54fd810>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fa5a55efb60>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/fastapi/applications.py", line 1135, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
                           │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
                           └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
  File "/home/hum/gradioenv/lib/python3.13/site-packages/starlette/applications.py", line 107, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │                │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │                └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fa5a5302660>
          └ <fastapi.applications.FastAPI object at 0x7fa5a54fd810>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fa5a5302510>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fa5a5302660>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/starlette/middleware/exceptions.py", line 49, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7fa5a53023c0>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fa5a5302510>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │   │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │   └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <fastapi.routing.APIRouter object at 0x7fa5d3e1a9e0>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7fa5a53023c0>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │                │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │                └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x7fa5d3e1a9e0>>
          └ <fastapi.routing.APIRouter object at 0x7fa5d3e1a9e0>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/starlette/routing.py", line 725, in app
    await self.lifespan(scope, receive, send)
          │    │        │      │        └ <bound method LifespanOn.send of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │        │      └ <bound method LifespanOn.receive of <uvicorn.lifespan.on.LifespanOn object at 0x7fa5a5301940>>
          │    │        └ {'type': 'lifespan', 'asgi': {'version': '3.0', 'spec_version': '2.0'}, 'state': {}, 'app': <fastapi.applications.FastAPI obj...
          │    └ <function Router.lifespan at 0x7fa65b1b4ae0>
          └ <fastapi.routing.APIRouter object at 0x7fa5d3e1a9e0>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/starlette/routing.py", line 694, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               │    │                └ <fastapi.applications.FastAPI object at 0x7fa5a54fd810>
               │    └ <function create_app.<locals>.lifespan at 0x7fa5a53a8360>
               └ <fastapi.routing.APIRouter object at 0x7fa5d3e1a9e0>
  File "/usr/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
                       │    └ <async_generator object create_app.<locals>.lifespan at 0x1cfe3600>
                       └ <contextlib._AsyncGeneratorContextManager object at 0x7fa5a53027b0>

  File "/home/hum/gradioenv/ACE-Step-1.5/acestep/api_server.py", line 1623, in lifespan
    status_msg, ok = handler.initialize_service(
                     │       └ <function AceStepHandler.initialize_service at 0x7fa5a6bcbba0>
                     └ <acestep.handler.AceStepHandler object at 0x7fa5a5302900>

> File "/home/hum/gradioenv/ACE-Step-1.5/acestep/handler.py", line 428, in initialize_service
    self.model = self.model.to(device).to(self.dtype)
    │    │       │    │     │  │          │    └ torch.bfloat16
    │    │       │    │     │  │          └ <acestep.handler.AceStepHandler object at 0x7fa5a5302900>
    │    │       │    │     │  └ 'cuda'
    │    │       │    │     └ <function Module.to at 0x7fa5c45b2160>
    │    │       │    └ AceStepConditionGenerationModel(
    │    │       │        (decoder): AceStepDiTModel(
    │    │       │          (rotary_emb): Qwen3RotaryEmbedding()
    │    │       │          (layers): ModuleL...
    │    │       └ <acestep.handler.AceStepHandler object at 0x7fa5a5302900>
    │    └ AceStepConditionGenerationModel(
    │        (decoder): AceStepDiTModel(
    │          (rotary_emb): Qwen3RotaryEmbedding()
    │          (layers): ModuleL...
    └ <acestep.handler.AceStepHandler object at 0x7fa5a5302900>

  File "/home/hum/gradioenv/lib/python3.13/site-packages/transformers/modeling_utils.py", line 4343, in to
    return super().to(*args, **kwargs)
                       │       └ {}
                       └ ('cuda',)
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1371, in to
    return self._apply(convert)
           │    │      └ <function Module.to.<locals>.convert at 0x7fa5a53aaca0>
           │    └ <function Module._apply at 0x7fa5e5db5580>
           └ AceStepConditionGenerationModel(
               (decoder): AceStepDiTModel(
                 (rotary_emb): Qwen3RotaryEmbedding()
                 (layers): ModuleL...
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
    │      │      └ <function Module.to.<locals>.convert at 0x7fa5a53aaca0>
    │      └ <function Module._apply at 0x7fa5e5db5580>
    └ AceStepConditionEncoder(
        (text_projector): Linear(in_features=1024, out_features=2048, bias=False)
        (lyric_encoder): AceSt...
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
    │      │      └ <function Module.to.<locals>.convert at 0x7fa5a53aaca0>
    │      └ <function Module._apply at 0x7fa5e5db5580>
    └ AceStepTimbreEncoder(
        (embed_tokens): Linear(in_features=64, out_features=2048, bias=True)
        (norm): Qwen3RMSNorm((2048,), ...
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
    │      │      └ <function Module.to.<locals>.convert at 0x7fa5a53aaca0>
    │      └ <function Module._apply at 0x7fa5e5db5580>
    └ ModuleList(
        (0-3): 4 x AceStepEncoderLayer(
          (self_attn): AceStepAttention(
            (q_proj): Linear(in_features=2048, out...
  [Previous line repeated 3 more times]
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 957, in _apply
    param_applied = fn(param)
                    │  └ Parameter containing:
                    │    tensor([[ 0.0115,  0.0278, -0.0151,  ..., -0.0250,  0.0212, -0.0038],
                    │            [ 0.0069,  0.0055,  0.005...
                    └ <function Module.to.<locals>.convert at 0x7fa5a53aaca0>
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1357, in convert
    return t.to(
           │ └ <method 'to' of 'torch._C.TensorBase' objects>
           └ Parameter containing:
             tensor([[ 0.0115,  0.0278, -0.0151,  ..., -0.0250,  0.0212, -0.0038],
                     [ 0.0069,  0.0055,  0.005...

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacity of 3.94 GiB of which 3.69 MiB is free. Including non-PyTorch memory, this process has 3.93 GiB memory in use. Of the allocated memory 3.86 GiB is allocated by PyTorch, and 14.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR:    Traceback (most recent call last):
  File "/home/hum/gradioenv/lib/python3.13/site-packages/starlette/routing.py", line 694, in lifespan
    async with self.lifespan_context(app) as maybe_state:
               ~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/lib/python3.13/contextlib.py", line 214, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hum/gradioenv/ACE-Step-1.5/acestep/api_server.py", line 1635, in lifespan
    raise RuntimeError(status_msg)
RuntimeError: ❌ Error initializing model: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacity of 3.94 GiB of which 3.69 MiB is free. Including non-PyTorch memory, this process has 3.93 GiB memory in use. Of the allocated memory 3.86 GiB is allocated by PyTorch, and 14.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Traceback:
Traceback (most recent call last):
  File "/home/hum/gradioenv/ACE-Step-1.5/acestep/handler.py", line 428, in initialize_service
    self.model = self.model.to(device).to(self.dtype)
                 ~~~~~~~~~~~~~^^^^^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/transformers/modeling_utils.py", line 4343, in to
    return super().to(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1371, in to
    return self._apply(convert)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  [Previous line repeated 3 more times]
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 957, in _apply
    param_applied = fn(param)
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1357, in convert
    return t.to(
           ~~~~^
        device,
        ^^^^^^^
        dtype if t.is_floating_point() or t.is_complex() else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        non_blocking,
        ^^^^^^^^^^^^^
    )
    ^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacity of 3.94 GiB of which 3.69 MiB is free. Including non-PyTorch memory, this process has 3.93 GiB memory in use. Of the allocated memory 3.86 GiB is allocated by PyTorch, and 14.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)


ERROR:    Application startup failed. Exiting.
[API Server] Initializing models at startup...

============================================================
[API Server] GPU Configuration Detected:
============================================================
  GPU Memory: 3.94 GB
  Configuration Tier: tier1
  Max Duration (with LM): 180s
  Max Duration (without LM): 180s
  Max Batch Size (with LM): 1
  Max Batch Size (without LM): 1
  Default LM Init: False
  Available LM Models: None
============================================================

[API Server] Auto-enabling CPU offload (GPU < 16GB)
[API Server] Auto-setting offload_to_cpu=True based on GPU memory
[Model Download] Model acestep-v15-turbo already exists at /home/hum/gradioenv/ACE-Step-1.5/checkpoints/acestep-v15-turbo
[Model Download] Model vae already exists at /home/hum/gradioenv/ACE-Step-1.5/checkpoints/vae
[API Server] Loading primary DiT model: acestep-v15-turbo
[API Server] ERROR: Primary model failed to load: ❌ Error initializing model: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacity of 3.94 GiB of which 3.69 MiB is free. Including non-PyTorch memory, this process has 3.93 GiB memory in use. Of the allocated memory 3.86 GiB is allocated by PyTorch, and 14.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

Traceback:
Traceback (most recent call last):
  File "/home/hum/gradioenv/ACE-Step-1.5/acestep/handler.py", line 428, in initialize_service
    self.model = self.model.to(device).to(self.dtype)
                 ~~~~~~~~~~~~~^^^^^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/transformers/modeling_utils.py", line 4343, in to
    return super().to(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1371, in to
    return self._apply(convert)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 930, in _apply
    module._apply(fn)
    ~~~~~~~~~~~~~^^^^
  [Previous line repeated 3 more times]
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 957, in _apply
    param_applied = fn(param)
  File "/home/hum/gradioenv/lib/python3.13/site-packages/torch/nn/modules/module.py", line 1357, in convert
    return t.to(
           ~~~~^
        device,
        ^^^^^^^
        dtype if t.is_floating_point() or t.is_complex() else None,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        non_blocking,
        ^^^^^^^^^^^^^
    )
    ^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB. GPU 0 has a total capacity of 3.94 GiB of which 3.69 MiB is free. Including non-PyTorch memory, this process has 3.93 GiB memory in use. Of the allocated memory 3.86 GiB is allocated by PyTorch, and 14.67 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
</details>

Not running anything else on the GPU, nvidia-smi shows 2Mib / 4096Mib before trying to start the API server.

**Comment by hum-ma** [comment]
Same error when running Gradio UI server with API enabled as in `python -m acestep.acestep_v15_pipeline --enable-api`

The `--offload_dit_to_cpu True` option allows it to initialize but then it immediately runs out of memory when trying to load the model to GPU to generate music.

The root cause seems to be that when the model is initialized at start-up it's not quantized, as opposed to when it's initialized from the UI. There isn't currently a command-line option related to compilation or quantization, instead `compile_model=False` is hard-coded in these cases.

So, a patch for acestep/acestep_v15_pipeline.py to allow quantization could be something as simple as this:

```
149a150
>     parser.add_argument("--quantize", type=str, default=None, choices=["int8_weight_only", "fp8_weight_only", "w8a8_dynamic"], help="DiT model quantization (optional)")
251c252,253
<                 compile_model=False,
---
>                 compile_model=True if args.quantize else False,
>                 quantization=args.quantize,
```

And for api_server.py some similar changes. This way it works for me so maybe I could create a PR. I wonder if there might be any reason to enable the model to be compiled without quantizing it?
